#%RAML 1.0
title: Doctus-Day4-hello-world

/hello:
  get:
    description: get hello world
    responses:
      200:
        body:
          application/json:
            example: {"status": "Hello World"}